version: '3'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    networks: 
      - storage-azure
    ports:
      - 10000:10000
      - 10001:10001

networks: 
  storage-azure:
    driver: bridge